name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5.0.2
        with:
          go-version-file: go.mod
          cache: true

      - uses: goreleaser/goreleaser-action@v5.1.0
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
